### ISSUE TITLE
zsh keybindings: install as subcommand of httm

### ISSUE THREAD

**Issue by bketelsen** [kimono-koans/httm#10]
`httm` should provide an option to create the keybindings file somewhere and source it from the user's `.zshrc`.

e.g. create `$XDG_CONFIG/httm`, put the zsh keybindings there, and append `source $XDG_CONFIG/httm/zsh-keybindings.zsh` to `.zshrc`

**Comment by kimono-koans** [comment]
Thanks for this suggestion!  Finally gave me an opportunity to use `include_str!`

For the feature, see: https://github.com/kimono-koans/httm/commit/5478458f698c02e1a93f20cc4664ba8ce311b83e
