### ISSUE TITLE
Better name

### ISSUE THREAD

**Issue by danboid** [kimono-koans/httm#104]
Why is the program called `httm`? Is that an acronym? If so, what does it stand for? This isn't currently explained in the README.

`httm` is totally unmemorable IMO and I'd expect it would be a http tool of some sort like a webserver, if I had to guess from its name. I always prefer it when programs have names that represent what they do so how about changing the program name to something more memorable and descriptive like `snapfind` or `snapsearch`? I think it would help with adoption.

Thanks

**Comment by kimono-koans** [comment]
> Why is the program called httm? Is that an acronym? If so, what does it stand for? This isn't currently explained in the README.

Perhaps it's a [generational thing](https://en.wikipedia.org/wiki/Hot_Tub_Time_Machine)?  I do believe I [reference it](https://github.com/kimono-koans/httm#i-know-what-youre-thinking-but-slow-your-roll) in the README though.

> I always prefer it when programs have names that represent what they do so how about changing the program name to something more memorable and descriptive like snapfind or snapsearch?

Ugh, gross.  No.
