### ISSUE TITLE
Using with btrbk:  Error: No snaps found for mount: "/var/lib/docker/btrfs"

### ISSUE THREAD

**Issue by HaleTom** [kimono-koans/httm#108]
I use [`btrbk`](https://github.com/digint/btrbk) for creating hourly snapshots of my btrfs filesystem.

`httm` doesn't seem able to find any snapshots:
```
% sudo httm --list-snaps
Error: No snaps found for mount: "/var/lib/docker/btrfs"
%
% ls /mnt/btrfs-vol/home/btrbk/home | head -n3
home.20240218T1346/  home.20240228T1400/  home.20240302T2302/
home.20240219T0901/  home.20240228T1500/  home.20240303T0000/
home.20240220T1650/  home.20240228T1600/  home.20240303T1425/
```

I read the man page, but couldn't find a way to specify where to look for my snapshots.

-------

**Additional context**
Add any other context about the problem here.  Perhaps you should include system details like:

 - httm 0.37.0
 - OS: Manjaro using httm-bin package
 - Relevant filesystem/s: btrfs
 - `httm --debug` output if applicable:
       % sudo httm --debug
       Error: No snaps found for mount: "/var/lib/docker/btrfs"

**Comment by HaleTom** [comment]
Reading #102 didn't seem to shed any light.

**Comment by kimono-koans** [comment]
I recently modified `httm` to return errors for certain btrfs conditions, when perhaps warnings would have been more appropriate. 

I'm certain your issue stems from this.  I should merge soon.  Until then, I've started a branch to modify all such conditions which might result in an error to just spew a warning.  See: https://github.com/kimono-koans/httm/tree/fix_btrfs_errors

Instructions on how to build from source are contained within the [README](https://github.com/kimono-koans/httm/blob/master/README.md)

Thanks for your bug report.

**Comment by HaleTom** [comment]
I seem to be having issues with this command:
```
% cargo install --locked --git https://github.com/kimono-koans/httm.git --tag fix_btrfs_errors
    Updating git repository `https://github.com/kimono-koans/httm.git`
error: failed to find tag `fix_btrfs_errors`

Caused by:
  reference 'refs/remotes/origin/tags/fix_btrfs_errors' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by HaleTom** [comment]
GPT to the rescue -- I needed `--branch` not `--tag` in this instance.

**Comment by kimono-koans** [comment]
https://github.com/kimono-koans/httm/pull/111

**Comment by kimono-koans** [comment]
FYI, you're also executing without specifying a path/s.  `httm` operates like `sort` or `cat` in that it will accept input from `stdin`.  This is so `find /usr/bin | httm` just works.  `--list-snaps` is also  a ZFS only option.  One which you can get with `btrfs sub list /mnt`.  See the README and `--help` for more information.

**Comment by HaleTom** [comment]
@kimono-koans I confirm that [`fix_btrfs_errors`](https://github.com/kimono-koans/httm/tree/fix_btrfs_errors?rgh-link-date=2024-03-13T11%3A06%3A51Z) does proceed to list some snapshots.  Cheers!
