### ISSUE TITLE
error: invalid value 'httmSnapFileMount' for '--snap[=<SNAPSHOT>]'

### ISSUE THREAD

**Issue by promisedlandt** [kimono-koans/httm#123]
**Describe the bug**

I just installed httm and tried to use `httm -S .`.  I get the output 

```sh
error: invalid value 'httmSnapFileMount' for '--snap[=<SNAPSHOT>]'
  [possible values: snap-file, snapshot, snap-file-mount]

  tip: a similar value exists: 'snap-file-mount'

For more information, try '--help'.
```

The help output reads "snapshot a file/s most immediate mount. **This argument optionally takes a value for a snapshot suffix.** The default suffix is 'httmSnapFileMount'. Note: This is a ZFS only option which requires either superuser or 'zfs allow' privileges. **[possible values: snap-file, snapshot, snap-file-mount]**" (emphasis added).  

Did maybe something go wrong in https://github.com/kimono-koans/httm/commit/7d2020fa36f1c358f1b6551067f0e8c36462d549#diff-23f5b9ce1dd89ac0d57d75979300b16283ac4c44b1e79c06d9f483f095547d53R267 ?

**Expected behavior**

I expected a snapshot with the suffix "httmSnapFileMount" to be taken.

**Additional context**

 - `httm` version: httm 0.39.0
 - Relevant filesystem/s: [e.g. ZFS or btrfs]: zfs-2.1.11-1

**Comment by kimono-koans** [comment]
Appreciate you filing a bug report.  

This probably has something to do with upgrading a dependency (clap) to the latest version.  Shouldn't be too hard to fix (famous last words!).

**Comment by kimono-koans** [comment]
This should fix: https://github.com/kimono-koans/httm/commit/318ac9b21fa867c3d6a1386c35bfd668abdd6e07

Will do a minor release soon.

**Comment by promisedlandt** [comment]
Thank you for the quick fix and release. I can confirm that it fixes the issue for me.
