### ISSUE TITLE
Error mounting local snapshots under MacOS - is this error related to "not for use with ... direct attached storage"?

### ISSUE THREAD

**Issue by e12e** [kimono-koans/httm#126]
**Before you begin**

1. Have you tried with the latest version of `httm`? Via "brew", yes. See below.
2. Have you read the README and/or the help (`httm -h` or `man httm`)? Yes.
3. Is this actually a bug report? I belive so.

This might be the a case of unclear error message and wrong use (TimeMachine and DAS).

**Describe the bug**
Running `sudo equine --mount-local`results in "Operation not permitted" error:

```bash
sudo equine --mount-local
Discovering backup locations (this can take a few seconds)...
Mounting snapshots...
mkdir: /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/emily.local: Operation not permitted
```

**To Reproduce**
1. `sudo equine --mount-local`
2. See error

Possibly related - opening the native macOS TimeMachine UI to verify that TimeMachine is working (maybe it sets up some protected mounts that conflict with httm?).

**Expected behavior**
Either TimeMachine snapshots should be mounted, or if it is possible to check if the use-case is unsupported,
an error/hint to that effect should be output ("Unable to create folder for mount points - this could be due to
trying to use httm with direct attached storage").

**Additional context**
I'm trying to run this on an m2 MacBook Air, with TimeMachine on an external usb3 ssd drive. I am a little uncertain if this is what is reffered to as unsupported use-case (direct attached storage, DAS). Technically it certainly is a DAS, on the other hand I would
expect httm to either fail gracefully/earlier, fail at something other than permission for creating folder for mount-points, or simiply
fail quietly and horribly when/if the DAS is removed :-) ).

The error is certainly consistent with the errors I can provoke manually - so I'm wondering if there's some other edge case here with MacOS version?

IE:
```bash
# I have snapshots:
tmutil listlocalsnapshots /System/Volumes/Data | head -3
Snapshots for disk /System/Volumes/Data:
com.apple.TimeMachine.2024-07-22-202810.local
com.apple.TimeMachine.2024-07-22-212819.local

# There's something odd with access rights to the TimeMachine volume path:
sudo stat /Volumes/com.apple.TimeMachine.localsnapshots/
16777239 72984296 drwxr-xr-x 3 root wheel 0 96 "Jul 23 19:36:06 2024" "Jul 23 19:36:06 2024" "Jul 23 19:36:06 2024" "Jul 23 19:36:06 2024" 4096 0 0 /Volumes/com.apple.TimeMachine.localsnapshots/

sudo ls /Volumes/com.apple.TimeMachine.localsnapshots/
ls: /Volumes/com.apple.TimeMachine.localsnapshots/: Operation not permitted

sudo mkdir -p /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/emily.local
mkdir: /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/emily.local: Operation not permitted

# I have mounts of snapshots:
mount |grep -E '2024-07-22-(202810|212819)/(ventura|Data)'
com.apple.TimeMachine.2024-07-22-212819.local@/dev/disk4s1 on /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/emily/2024-07-22-212819/ventura - Data (apfs, local, read-only, journaled, nobrowse, protect)
com.apple.TimeMachine.2024-07-22-202810.local@/dev/disk4s1 on /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/emily/2024-07-22-202810/ventura - Data (apfs, local, read-only, journaled, nobrowse, protect)
com.apple.TimeMachine.2024-07-22-212819.local@/dev/disk4s5 on /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/emily/2024-07-22-212819/Data (apfs, local, read-only, journaled, nobrowse, protect)
com.apple.TimeMachine.2024-07-22-202810.local@/dev/disk4s5 on /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/emily/2024-07-22-202810/Data (apfs, local, read-only, journaled, nobrowse, protect)
```

(Note that httm wants to make a mountpoint "emily.local" while these are "emily" (just `hostname`).

 - `httm` version: 0.40.0
 - OS: macOS 14.5
 - Relevant filesystem/s: apfs

```console
system_profiler SPSoftwareDataType -detailLevel mini
Software:

    System Software Overview:

      System Version: macOS 14.5 (23F79)
      Kernel Version: Darwin 23.5.0
      Time since boot: 7 days, 7 hours, 8 minutes

uname -av
Darwin emily.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 arm64
```

**Comment by kimono-koans** [comment]
My initial guess is this has something to do with your hostname.  MacOS may not want you to use `emily.local` in this instance.  `.local` is usually added to a hostname like `emily` as part of a link local mDNS address.  Here, it is part of your hostname and that unusual hostname may conflict with the naming conventions MacOS wants you to use.  

A further guess is the `.` is the issue such that MacOS wouldn't want you to use any hostname with a `.` and automatically shortens your local snapshots directory to simply `emily`.

My recommendation to root cause: 

1. Restart the system or start in an otherwise clean state (by unmounting all Time Machine drives).  `mount` output should be clean of snapshots.
2. Start a normal TM backup.
3. MacOS will automatically create some directory for local snapshots `/Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb`
4. Write down the name it uses for your host.
5. Return somehow to an otherwise clean state.
6. Try to create that directory for your hostname yourself by using `sudo mkdir -p ...` in `/Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb`.  If this doesn't work, there may be a permissions issue on the directory.  Check its permissions.
7. Report back that directory's name to me.

**Comment by e12e** [comment]
Looks like having DAS attached was the core issue - see end of message.

> I don't have the same permissions issue on my Macbook. I am also running 14.5 with SIP fully enabled.

Ok. Odd.

>  equine --mount-local snapshots shouldn't implicate any DAS specific issues.

Right, that was my thought as well.

It's defintly TimeMachine that controls `/Volumes/com.apple.TimeMachine.localsnapshots` - while looking at it now it dissappeared from under /Volumes as the current backup completed. Then when opening the TimeMachine UI it reappeared again.

I struggle to make my machine reveal any hidden flags etc - it appears to be entirely normal:

```sh
ls -lO@d /Volumes/com.apple.TimeMachine.localsnapshots
drwxr-xr-x  3 root  wheel  - 96 Jul 26 17:05 /Volumes/com.apple.TimeMachine.localsnapshots
```
However anything under localsnapshots is mounted nobrowse, protect - but I can't find out how the parent folder itself is locked, eg:

```sh
ount |grep Backups.backupdb|head -1
com.apple.TimeMachine.2024-07-26-155229.local@/dev/disk4s1 on /Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/emily/2024-07-26-155229/ventura - Data (apfs, local, read-only, journaled, nobrowse, protect)
```

I can (as root) create folders under /Volumes as expected.

After disconnecting my backup drive, I can run `equine --mount-local` without error - but that is probably just because it can't find any snapshots, and so doesn't try to create any folders/mounts....?

Although, there should be some:

```sh
tmutil listlocalsnapshots /System/Volumes/Data 
Snapshots for disk /System/Volumes/Data:
com.apple.TimeMachine.2024-07-25-174739.local
com.apple.TimeMachine.2024-07-25-184741.local
com.apple.TimeMachine.2024-07-25-194812.local
#(... snip ...)
com.apple.TimeMachine.2024-07-26-155229.local
com.apple.TimeMachine.2024-07-26-165245.local
```

I guess this can be closed as trying to use httm with DAS for TimeMachine - which isn't supported.
