### ISSUE TITLE
Improve BTRFS docs

### ISSUE THREAD

**Issue by danboid** [kimono-koans/httm#140]
I have previously successfully used httm with ZFS as a non-root user but I've not been able to get it working yet with BTRFS and snapper generated snapshots as a non root user.

I can see snapper does get a mention in the httm README but I think the docs would benefit from more detail for BTRFS users because its not as straightforward as ZFS, as you know, there being more config options for BTRFS snapshots.

Is it possible for non-root users who don't have sudo access to use httm with btrfs and snapper created snsapshots? I have enabled my user to have rw access to their snapshots subvolume dir and I have also enabled that user in the "ALLOW_USER" snapper config setting so that they can run the snapper command to list snapshots.

Every time I have tried running `httm` as a non-root user with btrfs I get these errors:

```
WARN: btrfs mounts detected.  User must have super user permissions to determine the location of btrfs snapshots
NOTICE: Falling back to detection of btrfs snapshot mounts perhaps defined by Snapper re: mount: "/home"
ERROR: None of the selected strings could be converted to paths.
```

If the user doesn't have super user permissions, how do I tell `httm` where the snapshots are? They're in the standard snapper location (~/.snapshots) so I expected `httm` would find them without me having to tell it where they are. Is it not actually snapper aware?

Surely `httm`should be able to work without sudo as long as it has at least 500 permissions on the ~/.snapshots dir? If not, why not? I only really want to use it for giving users an easy way to undelete files that are present in their snapshots. ZFS users only have read access to ~./.zfs so why does `httm` require more permissions for BTRFS?

Thanks

**Comment by kimono-koans** [comment]
> Is it possible for non-root users who don't have sudo access to use httm with btrfs and snapper created snsapshots?

This should work.  

Could you provide some debug output (for example, `httm --debug /var/log/syslog`) and output of your `mount` command?

**Comment by danboid** [comment]
```
$ httm -r -d --debug httmlog ~
WARN: btrfs mounts detected.  User must have super user permissions to determine the location of btrfs snapshots
NOTICE: Falling back to detection of btrfs snapshot mounts perhaps defined by Snapper re: mount: "/home"
WARN: httm relies on the user (and/or the filesystem's auto-mounter) to mount snapshots.  Make certain any snapshots the user may want to view are mounted, or are able to be mounted, and/or the user has the correct permissions to view.
WARN: Mount "/home" appears to have no snapshots available.
Error: May only specify one path in the display recursive or interactive modes.
```

httm it saysa no to outputting a debug log for me.

```
$ httm --version
httm 0.43.2
```

Mount info:

```
# mount
/dev/sdc1 on / type ext4 (rw,relatime,discard,errors=remount-ro)
devtmpfs on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=65919140k,nr_inodes=16479785,mode=755,inode64)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=26368772k,nr_inodes=819200,mode=755,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=10270)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
ramfs on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
/var/lib/snapd/snaps/canonical-livepatch_282.snap on /snap/canonical-livepatch/282 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/canonical-livepatch_286.snap on /snap/canonical-livepatch/286 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/certbot_4182.snap on /snap/certbot/4182 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/core20_2379.snap on /snap/core20/2379 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/core20_2434.snap on /snap/core20/2434 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/core22_1621.snap on /snap/core22/1621 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/lxd_29351.snap on /snap/lxd/29351 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/core22_1663.snap on /snap/core22/1663 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/snapd_21759.snap on /snap/snapd/21759 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/core24_609.snap on /snap/core24/609 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/var/lib/snapd/snaps/snapd_22991.snap on /snap/snapd/22991 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
/dev/sdb1 on /dbs type ext4 (rw,relatime,discard,errors=remount-ro)
/dev/sdc15 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/sda1 on /home type btrfs (rw,nosuid,nodev,relatime,discard=async,space_cache=v2,subvolid=257,subvol=/@home)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,size=26368772k,nr_inodes=819200,mode=755,inode64)
nsfs on /run/snapd/ns/lxd.mnt type nsfs (rw)
nsfs on /run/snapd/ns/canonical-livepatch.mnt type nsfs (rw)
/dev/sdd1 on /mnt type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096,x-systemd.after=cloud-init.service,_netdev)
/var/lib/snapd/snaps/certbot_4193.snap on /snap/certbot/4193 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide)
tmpfs on /run/user/1002 type tmpfs (rw,nosuid,nodev,relatime,size=13184384k,nr_inodes=3296096,mode=700,uid=1002,gid=1003,inode64)
```

Subvolumes:


```
# btrfs subvol list /home/
ID 257 gen 1645 top level 5 path @home
ID 262 gen 1588 top level 257 path test1
ID 270 gen 1645 top level 257 path testuser
ID 271 gen 1644 top level 257 path leeg
ID 272 gen 1573 top level 257 path stefanp
ID 273 gen 1587 top level 257 path thomasb
ID 274 gen 1572 top level 257 path oyusuf
ID 276 gen 1645 top level 257 path .snapshots
ID 277 gen 1534 top level 271 path leeg/.snapshots
ID 278 gen 1545 top level 274 path oyusuf/.snapshots
ID 279 gen 1202 top level 272 path stefanp/.snapshots
ID 280 gen 1512 top level 273 path thomasb/.snapshots
ID 281 gen 1282 top level 270 path testuser/.snapshots
ID 282 gen 1140 top level 276 path .snapshots/1/snapshot
ID 283 gen 1141 top level 277 path leeg/.snapshots/1/snapshot
ID 284 gen 1142 top level 278 path oyusuf/.snapshots/1/snapshot
ID 285 gen 1143 top level 279 path stefanp/.snapshots/1/snapshot
ID 286 gen 1144 top level 281 path testuser/.snapshots/1/snapshot
ID 287 gen 1145 top level 280 path thomasb/.snapshots/1/snapshot
ID 289 gen 1150 top level 277 path leeg/.snapshots/2/snapshot
ID 290 gen 1151 top level 278 path oyusuf/.snapshots/2/snapshot
ID 291 gen 1152 top level 279 path stefanp/.snapshots/2/snapshot
ID 292 gen 1153 top level 281 path testuser/.snapshots/2/snapshot
ID 293 gen 1154 top level 280 path thomasb/.snapshots/2/snapshot
ID 295 gen 1158 top level 277 path leeg/.snapshots/3/snapshot
ID 296 gen 1159 top level 278 path oyusuf/.snapshots/3/snapshot
ID 297 gen 1160 top level 279 path stefanp/.snapshots/3/snapshot
ID 298 gen 1161 top level 281 path testuser/.snapshots/3/snapshot
ID 299 gen 1162 top level 280 path thomasb/.snapshots/3/snapshot
ID 301 gen 1166 top level 277 path leeg/.snapshots/4/snapshot
ID 302 gen 1167 top level 278 path oyusuf/.snapshots/4/snapshot
ID 303 gen 1168 top level 279 path stefanp/.snapshots/4/snapshot
ID 304 gen 1169 top level 281 path testuser/.snapshots/4/snapshot
ID 305 gen 1170 top level 280 path thomasb/.snapshots/4/snapshot
ID 307 gen 1189 top level 277 path leeg/.snapshots/5/snapshot
ID 308 gen 1190 top level 278 path oyusuf/.snapshots/5/snapshot
ID 309 gen 1191 top level 279 path stefanp/.snapshots/5/snapshot
ID 310 gen 1192 top level 280 path thomasb/.snapshots/5/snapshot
ID 312 gen 1204 top level 280 path thomasb/.snapshots/6/snapshot
ID 317 gen 1232 top level 276 path .snapshots/11/snapshot
ID 341 gen 1316 top level 276 path .snapshots/35/snapshot
ID 365 gen 1399 top level 276 path .snapshots/59/snapshot
ID 389 gen 1481 top level 276 path .snapshots/83/snapshot
ID 398 gen 1509 top level 276 path .snapshots/92/snapshot
ID 399 gen 1518 top level 276 path .snapshots/93/snapshot
ID 400 gen 1535 top level 276 path .snapshots/94/snapshot
ID 401 gen 1541 top level 276 path .snapshots/95/snapshot
ID 402 gen 1551 top level 276 path .snapshots/96/snapshot
ID 403 gen 1568 top level 276 path .snapshots/97/snapshot
ID 404 gen 1574 top level 276 path .snapshots/98/snapshot
ID 405 gen 1577 top level 276 path .snapshots/99/snapshot
ID 406 gen 1589 top level 276 path .snapshots/100/snapshot
ID 407 gen 1591 top level 276 path .snapshots/101/snapshot
ID 408 gen 1593 top level 276 path .snapshots/102/snapshot
ID 409 gen 1595 top level 276 path .snapshots/103/snapshot
ID 410 gen 1597 top level 276 path .snapshots/104/snapshot
ID 411 gen 1600 top level 276 path .snapshots/105/snapshot
ID 412 gen 1603 top level 276 path .snapshots/106/snapshot
ID 413 gen 1606 top level 276 path .snapshots/107/snapshot
ID 414 gen 1609 top level 276 path .snapshots/108/snapshot
ID 415 gen 1612 top level 276 path .snapshots/109/snapshot
ID 416 gen 1615 top level 276 path .snapshots/110/snapshot
ID 417 gen 1618 top level 276 path .snapshots/111/snapshot
ID 418 gen 1621 top level 276 path .snapshots/112/snapshot
ID 419 gen 1624 top level 276 path .snapshots/113/snapshot
ID 420 gen 1627 top level 276 path .snapshots/114/snapshot
ID 421 gen 1630 top level 276 path .snapshots/115/snapshot
ID 422 gen 1633 top level 276 path .snapshots/116/snapshot
ID 423 gen 1636 top level 276 path .snapshots/117/snapshot
ID 424 gen 1642 top level 276 path .snapshots/118/snapshot
```

Thanks

**Comment by kimono-koans** [comment]
> $ httm -r -d --debug httmlog ~

Why not use the bare command with a file in your `/home` directory, as requested?  `httm -r -d ...` puts `httm` into a special display recursive mode.  Like: `find . -maxdepth 1 -type f | head -1 | httm --debug`

**Comment by danboid** [comment]
I might've got --debug to work?

```
testuser@poseidon:~$ httm -r -d --debug httmlog
WARN: btrfs mounts detected.  User must have super user permissions to determine the location of btrfs snapshots
NOTICE: Falling back to detection of btrfs snapshot mounts perhaps defined by Snapper re: mount: "/home"
WARN: httm relies on the user (and/or the filesystem's auto-mounter) to mount snapshots.  Make certain any snapshots the user may want to view are mounted, or are able to be mounted, and/or the user has the correct permissions to view.
WARN: Mount "/home" appears to have no snapshots available.
Config {
    paths: [
        PathData {
            path_buf: "/home/testuser/httmlog",
            metadata: None,
        },
    ],
    opt_recursive: false,
    opt_exact: false,
    opt_no_filter: false,
    opt_debug: true,
    opt_no_traverse: false,
    opt_omit_ditto: false,
    opt_no_hidden: false,
    opt_json: false,
    opt_one_filesystem: false,
    opt_no_clones: false,
    dedup_by: Metadata,
    opt_bulk_exclusion: None,
    opt_last_snap: None,
    opt_preview: None,
    opt_deleted_mode: Some(
        All,
    ),
    opt_requested_dir: None,
    requested_utc_offset: +00:00:00,
    exec_mode: Interactive(
        Restore(
            CopyOnly,
        ),
    ),
    print_mode: Formatted(
        Default,
    ),
    dataset_collection: FilesystemInfo {
        map_of_datasets: MapOfDatasets {
            inner: {
                "/home": DatasetMetadata {
                    source: "/dev/sda1",
                    fs_type: Btrfs(
                        Some(
                            BtrfsAdditionalData {
                                base_subvol: "/@home",
                                snap_names: OnceLock(
                                    <uninit>,
                                ),
                            },
                        ),
                    ),
                    link_type: Local,
                },
            },
        },
        map_of_snaps: MapOfSnaps {
            inner: {
                "/home": [],
            },
        },
        filter_dirs: FilterDirs {
            inner: {
                "/",
                "/boot/efi",
                "/dbs",
                "/dev",
                "/dev/hugepages",
                "/dev/mqueue",
                "/dev/pts",
                "/dev/shm",
                "/mnt",
                "/proc",
                "/proc/sys/fs/binfmt_misc",
                "/run",
                "/run/credentials/systemd-sysusers.service",
                "/run/lock",
                "/run/rpc_pipefs",
                "/run/snapd/ns",
                "/run/snapd/ns/canonical-livepatch.mnt",
                "/run/snapd/ns/lxd.mnt",
                "/run/user/1002",
                "/run/user/1011",
                "/snap/canonical-livepatch/282",
                "/snap/canonical-livepatch/286",
                "/snap/certbot/4182",
                "/snap/certbot/4193",
                "/snap/core20/2379",
                "/snap/core20/2434",
                "/snap/core22/1621",
                "/snap/core22/1663",
                "/snap/core24/609",
                "/snap/lxd/29351",
                "/snap/lxd/31333",
                "/snap/snapd/21759",
                "/snap/snapd/23258",
                "/sys",
                "/sys/firmware/efi/efivars",
                "/sys/fs/bpf",
                "/sys/fs/cgroup",
                "/sys/fs/fuse/connections",
                "/sys/fs/pstore",
                "/sys/kernel/config",
                "/sys/kernel/debug",
                "/sys/kernel/debug/tracing",
                "/sys/kernel/security",
                "/sys/kernel/tracing",
            },
        },
        opt_map_of_alts: None,
        opt_map_of_aliases: None,
        opt_common_snap_dir: None,
        opt_alt_store: None,
    },
    pwd: "/home/testuser",
}
ERROR: httm could find neither a live version, nor any snapshot version for all the specified paths, so, umm, 🤷? Please try another file.
```

**Comment by kimono-koans** [comment]
Below is from the `httm` README:

> Note: Users may need to use sudo (or equivalent) to view versions on BTRFS or NILFS2 datasets, or Restic repositories, as BTRFS or NILFS2 snapshots or Restic repositories may require root permissions in order to be visible. Restic and Time Machine backups also require an additional flag, see further discussion of Restic --alt-store in the below.

My best guess is you don't have permissions to view your `.snapshots` directory.

What are your permissions for the `.snapshots` directory?  If you cannot read the directory, or `cd` into the directory, because it is owned by root, then you will need to use `sudo` to view those snapshots.

**Comment by danboid** [comment]
No, I set the permissions to 500 on all users ~/.snapshots dirs and made the user the owner of that dir. My non-root user is able to browse the .snapshots dir OK.

`dr-x------ 1 testuser testuser    8 Nov 21 17:00 .snapshots`

**Comment by kimono-koans** [comment]
> No, I set the permissions to 500 on all users ~/.snapshots dirs and made the user the owner of that dir. My non-root user (testuser) is able to browse their ~/.snapshots dir OK.
> 

Okay, but what are the permissions of `/home/.snapshots` which is the only Snapper location which can be determined without the use of `sudo` and the `btrfs` command?  

The fact that each user has a `.snapshots` is fine, but `httm` won't pick up such directories when falling back to Snapper default mounts.  The only layout `httm` will pick up in fallback mode is the default layout `<mount>/.snapshots/<some number>/snapshot`.  So here that would be`/home/.snapshots/...`.  

AFAIK if you want to provide a layout which has Snapper snapshots for each user to use with `httm`, you must provide a new mount or subvolume for each user.

**Comment by danboid** [comment]
@home is a subvolume then each user (ie testuser) has their own subvolume beneath that.

I'm new to using snapper (and BTRFS too really) but my understanding is that snapper auto creates a new subvolume (.snapshots) beneath each users home dir/subvolume when you create a config for that user/subvol so every user has both their own subvolume and their own .snapshots subvolume beneath that. That is my understanding of how it works at least.

**Comment by kimono-koans** [comment]
> @home is a subvolume then each user (ie testuser) has their own subvolume beneath that.
> 
> I'm new to using snapper (and BTRFS too really) but my understanding is that snapper auto creates a new subvolume (.snapshots) beneath each users home dir/subvolume when you create a config for that user/subvol so every user has both their own subvolume and their own .snapshots subvolume beneath that. That is my understanding of how it works at least.

Okay, well it has to be a mount which is shown in your `/proc/mounts` for use with `httm` when falling back to defined mounts.  The only mount available to `httm` is then:

```
/dev/sda1 on /home type btrfs (rw,nosuid,nodev,relatime,discard=async,space_cache=v2,subvolid=257,subvol=/@home)
```

The problem is really BTRFS because BTRFS snapshots may be layed out in any which way the user wishes (which FYI is a pain in the balls to support).  `httm` does it's best to auto-discover using `btrfs`, when falling back there is no auto-discovery, there is only the default Snapper layout.

**Comment by danboid** [comment]
> > @home is a subvolume then each user (ie testuser) has their own subvolume beneath that.
> > I'm new to using snapper (and BTRFS too really) but my understanding is that snapper auto creates a new subvolume (.snapshots) beneath each users home dir/subvolume when you create a config for that user/subvol so every user has both their own subvolume and their own .snapshots subvolume beneath that. That is my understanding of how it works at least.
> 
> Okay, well it has to be a mount which is shown in your `/proc/mounts` for use with `httm` when falling back to defined mounts. The only mount available to `httm` is then:
> 
> ```
> /dev/sda1 on /home type btrfs (rw,nosuid,nodev,relatime,discard=async,space_cache=v2,subvolid=257,subvol=/@home)
> ```

Hmmm. Are you saying that if I add every every users subvol into fstab that might fix httm?


> 
> The problem is really BTRFS because BTRFS snapshots may be layed out in any which way the user wishes (which FYI is a pain in the balls to support). `httm` does it's best to auto-discover using `btrfs`, when falling back there is no auto-discovery, there is only the default Snapper layout.

Maybe so but snapper seem to be the most popular, most fully featured BTRFS snapshot tool (please correct me if I'm wrong) and it also has a default layout for where it makes its .snapshots subvols so as long as people stick to its defaults, which I think I have, then you would hope you'd be able to make it work?

**Comment by danboid** [comment]
It sounds like too much a security risk for me to give read access to the snapper group (or whatever I call it) to /home/.snapshots.

It sounds to me like httm only works with snapper if you have sudo access.

**Comment by kimono-koans** [comment]
> Hmmm. Are you saying that if I add every every users subvol into fstab that might fix httm?

It might?   Your permissions are also suspect.  I might tinker with those too.

> Maybe so but snapper seem to be the most popular, most fully featured BTRFS snapshot tool (please correct me if I'm wrong) and it also has a default layout for where it makes its .snapshots subvols so as long as people stick to its defaults, which I think I have, then you would hope you'd be able to make it work?

I could add other locations to search for Snapper defined snapshots (like: Snapper can also do this, if you do this...), but I don't care to learn Snapper well enough to make that happen by myself.  

If this is something that interests you, my suggestion is to learn Snapper and BTRFS well enough to determine other possible common layouts one can determine from only reading `/proc/mounts` and from a simple `readdir`/`opendir` on any snapshot directories, and explain that use case to me.  Then I might be interested enough to add.

Right now, I'm going to close this because any layout beyond the Snapper default is, as of now, unsupported. 

> It sounds to me like httm only works with snapper if you have sudo access but my users don't have sudo access.

No, `httm` only works with BTRFS and snapper when you use the default Snapper layouts and you have set sane permissions.  

You're right in one sense -- `httm` *isn't guaranteed* to work with BTRFS without `sudo`, and the README is very clear about this.   And if this is a problem for you, this is very clearly a BTRFS problem or a Snapper or user configuration problem, not an `httm` problem.

**Comment by danboid** [comment]
> > Hmmm. Are you saying that if I add every every users subvol into fstab that might fix httm?
> 
> It might? Your permissions are also suspect. I might tinker with those too.


Why are my permissions suspect?


> Right now, I'm going to close this because any layout beyond the Snapper default is, as of now, unsupported.

I am using snapper defaults, the only thing I change from the defaults is the number of snapshots which I reduced to a max of 10 per subvol. Everything else, like the location of the .snapshot subvolumes, is 100% OOTB standard.

**Comment by danboid** [comment]
My /home/.snapshots is owned by root and that's how I'd prefer to keep it to stop all users having (read) access to every snapshot.

**Comment by danboid** [comment]
I never did get httm working with snapper BTRFS snapshots for non-root users so I've written this:

https://github.com/danboid/SRT

It doesn't have anywhere near the number of features of httm but it does provide a quick and easy way for non-root users to restore snapper snapshots of their home dirs.
