### ISSUE TITLE
Snapshot metadata corruption - check for deleted files

### ISSUE THREAD

**Issue by TheDrifter363** [kimono-koans/httm#32]
Hi,

So I ran this command:
"httm -d -n -R --no-live ~ > deleted-files.txt"
and it caused high cpu usage, which locked out my server. I couldn't ssh or anything. So I did an unsafe poweroff, and then when I rebooted back up, I saw snapshot metadata corruption. I'm not sure what's going on. I'm nervous about repeating that command, so I don't know if it'll happen again. Just thought I should mention it.

**Comment by kimono-koans** [comment]
Appreciate you leaving a comment.  Never a good feeling for something like this to happen.

Can you tell me a little more about how this happened?  `httm -d -n -R --no-live ~ > deleted-files.txt` should print dots to stderr to show progress.  Did you see those dots at all?

A full system hang for which you cannot `ctrl + c` or `ssh` into the box sounds like a thread deadlock issue to me.  I've been trying out different concurrency models over this weekend and one of them may not work that well on your particular system.

If you do try again, would you try with the latest bits, or the latest tagged release?

**Comment by kimono-koans** [comment]
I'm going to close, but would be pleased to reopen later, if you have more information to add.
