### ISSUE TITLE
internal version was not bumped with `0.34.1` release

### ISSUE THREAD

**Issue by bevanjkay** [kimono-koans/httm#97]
Hi 👋, Homebrew maintainer here. We are seeing a regression test failure when trying to build the latest (`0.34.1`) version of httm.
It looks like the internal version was not bumped for the release.

```
Error: httm: failed
An exception occurred within a child process:
Minitest::Assertion: Expected: "httm 0.34.1"
Actual: "httm 0.34.0"
```
https://github.com/Homebrew/homebrew-core/pull/159842

**Comment by kimono-koans** [comment]
https://github.com/kimono-koans/httm/releases/tag/0.34.2 should remedy.

Long story short: My laptop had to be replaced and the scripts that should run on release didn't, and didn't fail well.

FYI, I am a long time Mac user, but I'm relatively new to homebrew (I had been using pkgsrc) and I'm very eager to make the homebrew package at least as good as the Debian package.

I am a mostly hobbyist developer, and although I care deeply about Rust, snapshots and storage (obviously), learning a great deal about GH actions or Ruby doesn't interest me in the same way.  That being said, making homebrew integration work well enough that I don't have worry about it, would be great.  

Is there some kind of quickstart guide re: integrating with your GH actions?  FWIW, right now, I do all my signing of packages locally with scripts, perhaps I can learn enough to stop doing that as well.

**Comment by bevanjkay** [comment]
We have an internal system called `livecheck` that can check if there is a new version available, and then a simple command `brew bump httm` that creates a PR to update the version. Homebrew distributes binaries built from source, and signed on CI during build. If generally speaking `httm` updates do not change the build structure, it could be added to our internal `autobump` workflow that checks for new versions from upstream every 15 minutes.
